version: '3.8'
services:
  yolo-model:
    build:
      context: ./yolo-model
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./yolo-model:/app
  mysql:
    image: mysql:8.0
    container_name: roomcheck-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: roomcheck_db
      MYSQL_USER: roomcheck_user
      MYSQL_PASSWORD: userpassword123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: roomcheck-backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: roomcheck_user
      DB_PASSWORD: userpassword123
      DB_NAME: roomcheck_db
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    command: npm run start

volumes:
  mysql_data:

 # 앱이라 필요없음
  # flutter-app:
  #   build:
  #     context: ./room-check-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - yolo-model