services:
  yolo-model:
    build:
      context: ./yolo-model
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./yolo-model:/app

  flutter-app:
    build:
      context: ./room-check-app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # volumes:
    #   - ./room-check-app:/app


  # backend-api:
  #   build: ./backend-api
  #   container_name: backend-api
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend-api:/app
  #   depends_on:
  #     - mysql

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: mydb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql